# Generated by Django 4.2.1 on 2023-11-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicians',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
