# Generated by Django 4.2.1 on 2023-11-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0002_musicians_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicians',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
