# Generated by Django 4.2.1 on 2023-11-27 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0005_categories_musicians_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicians',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musicians.categories'),
        ),
    ]
